### ISSUE TITLE
Get error when importing this into latest ADK

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/DroneKit-Android-Starter#4]
![image](https://cloud.githubusercontent.com/assets/5368500/11330877/d9db9ee0-9206-11e5-8751-d8fa19eb4249.png)

**Comment by 1ee7** [comment]
Hey,  I install the Hello drone on the cell phone, and setted up SITL on windows with cygwin. how to connect them with usb or udp? can anybody give me some clues,,,thanks

**Comment by hamishwillee** [comment]
Hi @1ee7 
Please raise this question on the [DroneKit Android forums](https://discuss.dronekit.io/c/android).
As a general rule, best not to hijack a github issue with an unrelated issue.

**Comment by hamishwillee** [comment]
This was fixed by #5
