### ISSUE TITLE
Sending mavlink command

### ISSUE THREAD

**Issue by tarazansafak** [3drobotics/DroneKit-Android-Starter#7]
Hello guys,

Is there any way to send mavlink commands given in this link using this drone-kit?
https://pixhawk.ethz.ch/mavlink/

if yes, can you please direct me to some points?

Thanks!

**Comment by m4gr3d** [comment]
@tarazansafak you can use the [`ExperimentalApi#sendMavLinkMessage(...)`](http://android.dronekit.io/javadoc/com/o3dr/android/client/apis/ExperimentalApi.html#sendMavlinkMessage%28com.o3dr.services.android.lib.mavlink.MavlinkMessageWrapper%29) to send mavlink commands directly.
